---
# Configure the Macbook
  - name: Setup the timezone
    ansible.builtin.command: systemsetup -settimezone {{ TZ }}
    become: yes
    tags: configure, tz

  - name: Setup zsh with oh-my-zsh
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{homedir_location}}/.oh-my-zsh"
    tags: configuration, zsh, ohmyzsh

  - name: Get the dracula theme for oh-my-zsh
    ansible.builtin.git:
      repo: https://github.com/dracula/zsh.git
      dest: "{{homedir_location}}/.oh-my-zsh_dracula_theme"
    tags: configuration, zsh, ohmyzsh

  - name: Symlink oh-my-zsh theme
    ansible.builtin.file:
      src: "{{homedir_location}}/.oh-my-zsh_dracula_theme/dracula.zsh-theme"
      dest: "{{homedir_location}}/.oh-my-zsh/themes/dracula.zsh-theme"
      state: link
    tags: configuration, zsh, ohmyzsh
