---
- name: Jumpstart a new macbook
  hosts: macbook
  tasks:
    - name: Install homebrew
      shell: 'yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"' 
      args:
        creates: /usr/local/bin/brew
      tags: install

    - name: Update homebrew 
      homebrew:
        state: latest
        update_homebrew: yes
      tags: install, update

    - name: Tap homebrew caskroom/cask
      homebrew_tap:
        tap: "homebrew/cask"
      tags: install, tap

    - name: Installing homebrew applications
      homebrew:
        name: "{{applications}}"
        state: latest
      tags: install, brew-apps

    - name: Installing homebrew cask applications
      homebrew_cask:
        name: "{{cask_applications}}"
        state: present
        install_options: force
      tags: install, cask-apps

    - name: Configure Macbook
      include: configure.yml
    
    - name: Install Dotfiles
      include: install_dotfiles.yml
    
