---
- name: Jumpstart a new macbook
  hosts: macbook
  gather_facts: true
  collections:
    - community.general
  vars:
    homebrew_paths:
      - /opt/homebrew/bin
      - /usr/local/bin

  pre_tasks:
    - name: Check Apple Silicon Homebrew path
      ansible.builtin.stat:
        path: /opt/homebrew/bin/brew
      register: brew_opt_homebrew
      tags: install

    - name: Check Intel Homebrew path
      ansible.builtin.stat:
        path: /usr/local/bin/brew
      register: brew_usr_local
      tags: install

    - name: Install Homebrew
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_opt_homebrew.stat.exists and not brew_usr_local.stat.exists
      changed_when: true
      tags: install

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: true
        path: "{{ homebrew_paths }}"
      tags: install, update

  tasks:

    - name: Install Homebrew formulas
      community.general.homebrew:
        name: "{{ brew_formulas }}"
        state: present
        path: "{{ homebrew_paths }}"
      tags: install, brew-apps

    - name: Install Homebrew cask applications
      community.general.homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
        path: "{{ homebrew_paths }}"
      tags: install, cask-apps

    - name: Configure Macbook
      ansible.builtin.include_tasks: configure.yml
      tags: configure
    
    - name: Install Dotfiles
      ansible.builtin.include_tasks: install_dotfiles.yml
      tags: dotfiles
    
